[build]
  # On lance le script JS AVANT le build Angular
  command = "node set-env.js && npm run build"
  publish = "dist/owasp-asvs-helper/browser"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200