[build]
  # Netlify installera les dépendances automatiquement. 
  # On ajoute la commande de build Angular standard.
  command = "npm run build"
  
  # Pour Angular 18+ SSR/Prerendering, le contenu statique 
  # se trouve généralement dans 'browser'
  publish = "dist/owasp-asvs-helper/browser"

[build.environment]
  NODE_VERSION = "20"
  # Au cas où vous garderiez ng2-charts v10, cette ligne est vitale :
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200